---
- name: Configure OSPFv2 on Arista switch
  hosts: switches
  gather_facts: false
  become: yes
  tasks:
    - name: Configure OSPFv2 on the switch
      arista.eos.eos_ospfv2:
        config:
          processes:
            - process_id: 1
              networks:
                - area: 0
                  prefix: "192.168.1.0/24"
                - area: 0
                  prefix: "192.168.2.0/24"

