---
- name: Configure OSPFv2 on Arista switch
  hosts: switches
  gather_facts: false
  become: yes
  connection: network_cli
  vars:
    ospf_interfaces:
      - Ethernet1
      - Ethernet2
      - Ethernet3
      - Ethernet4
      - Ethernet5
      - Ethernet6

  tasks:

    - name: Set interfaces as non-passive
      arista.eos.eos_config:
        lines:
          - "router ospf 1"
          - "no passive-interface {{ item }}"
        with_items: "{{ ospf_interfaces }}"
    - name: Debug OSPF configuration inputs
      debug:
        msg:
          - "Interfaces: {{ ospf_interfaces }}"

    - name: Configure OSPFv2 process and networks
      arista.eos.eos_config:
        lines:
          - "router ospf 1"
          - "network 192.168.1.0/24 area 0"
          - "network 192.168.2.0/24 area 0"
          - "passive-interface default"
          - "redistribute connected"


