---
- name: Configure VLANs on Arista switch
  hosts: switches
  gather_facts: false
  become: yes
  roles: 
    - vlan
  vars_prompt:
  - name: ansible_user
    prompt: "Enter the username"
    private: no
  - name: ansible_password
    prompt: "Enter the password"
    private: yes







    