---
- name: Configure OSPFv2 on Arista switch
  hosts: switches
  gather_facts: false
  become: yes
  tasks:
    - name: Merge provided config into running config
      arista.eos.eos_ospfv2:
        config:
          processes:
            - process_id: 1
              adjacency:
                exchange_start:
                  threshold: 20045623
              areas:
                - area_id: "0.0.0.2"
                  filter:
                    address: "10.1.1.0/24"
                - area_id: "0.0.0.50"
                  range:
                    address: "172.20.0.0/16"
                    cost: 34
              default_information:
                metric: 100
                metric_type: 1
                originate: true
              distance:
                intra_area: 85
              max_lsa:
                count: 8000
                ignore_count: 3
                ignore_time: 6
                reset_time: 20
                threshold: 40
              redistribute:
                - routes: "connected"
              passive_interface:
                - "default"  # Set all interfaces to passive