---
- name: parsing the configurations
  hosts: cisco9300
  gather_facts: no
  tasks:  
    - name: Configure the nested parents
      cisco.ios.ios_config:
        lines:
          - 10 permit ip host 192.168.10.10 any
          - 20 permit ip host 192.168.10.20 any
          - 30 permit ip host 192.168.20.30 any
          # - 40 permit ip host 192.168.10.40 any
          - 50 permit ip host 192.168.10.50 any
          - 60 permit ip host 192.168.10.60 any
          - 70 permit ip host 192.168.10.70 any
        parents: ip access-list extended demo_ac1 
        before: no ip access-list extended demo_ac1 
        match: exact
        replace: line # or block
      register: acl_output 

    - name: print the output
      ansible.builtin.debug:
          msg: "{{ acl_output }}"